### PR TITLE
feat: add bundle as config

### PR DESCRIPTION
**Pull request by maddhruv**
add esbuild bundle as an option to the config

### CODE REVIEW

**Comment by a7ul** [comment]
We cant bundle js in nodejs 

If we do that we ll need to figure out how to bundle native modules as well `.node` files.

That is the reason bundle option is not provided. 

Sorry but I ll close this pr aswell. Thanks for looking into this though @maddhruv

**Comment by nickcox** [comment]
I reckon there are plenty of use cases for bundling in node. That's why [esbuild supports it](https://esbuild.github.io/getting-started/#bundling-for-node), right? Our use case is that we like to deploy a relatively small bundle to AWS lambda.

**Comment by bl-ue** [comment]
@a7ul it's fine if native modules aren't bundled: https://esbuild.github.io/getting-started/#bundling-for-the-browser

>Sometimes the packages you want to use contain code that can't be bundled for some reason. An example of this is a package with native extensions such as `fsevents`. Or, you may want to exclude a package from the bundle for other reasons. This can be done by marking the package as external:

**Comment by bl-ue** [comment]
Can't you just mark those modules as external like [this](https://esbuild.github.io/getting-started/#bundling-for-the-browser)?
```js
require('esbuild').buildSync({
  entryPoints: ['app.jsx'],
  bundle: true,
  platform: 'node',
  external: ['fsevents'],  // <--
  outfile: 'out.js',
})
```

**Comment by lancetipton** [comment]
Completely wasted my time, until I found this. It makes no sense to **not** support and limit functionality of esbuild. I really don't understand the reasoning here?

That said, it's your repo and I fully support you doing whatever you want with it. 
Problem is now I have to fork it, and manage it myself for just a single boolean flag.

At the very least can you add a note in the Readme.md so others don't waste time like I did?
If it's already there and I missed it my apologies, but I could not find it anywhere other than this issue.

I actually dug through the code first, and [saw it was forced](https://github.com/a7ul/esbuild-node-tsc/blob/8ed7141df566d4cc468d4c8bc8870856f9cf89ff/src/index.ts#L99) to `false`,  and came to report an issue, which brought me here.

So while I support you doing whatever you want with your open-source repo, it would be nice to at least mention it, as the current Readme is misleading. This [part here](https://github.com/a7ul/esbuild-node-tsc/blob/8ed7141df566d4cc468d4c8bc8870856f9cf89ff/README.md?plain=1#L116) gives the assumption of full access to the esbuild config options.

**Comment by lancetipton** [comment]
Cloned the repo, and update to allow all esbuild options => https://www.npmjs.com/package/@ltipton/esb-node

**Pull request closed without merging**
